### ISSUE TITLE
Many events with a duration of 0

### ISSUE THREAD

**Issue by 8bitgentleman** [ActivityWatch/aw-android#34]
[As brought up on the forum](https://forum.activitywatch.net/t/activity-watch-mobile-query-error/520/6?u=8bitgentleman) many of the events in my aw-android have a duration of 0 seconds. Looking at my event list close to half of my events are a duration of 0 seconds. Not sure if this is actually a bug or what

![2ca7891a775ae6024037993a5ec93ea78b6e0925_2_628x1000](https://user-images.githubusercontent.com/4028391/78501901-11419b00-772c-11ea-81eb-c4e0a24efc48.jpg)

**Comment by nicolae-stroncea** [comment]
Apart from #39, another thing which causes 0 events is that events are stored with their classes, so if an app has multiple classes, events from separate classes will not get merged together(afaik) in the db.

This shouldn't cause any duration issues (apart from aesthetics) since events are repored by app, and events of same classname will be merged together
