### ISSUE TITLE
Allow to send data to a remote server

### ISSUE THREAD

**Issue by kamaradclimber** [ActivityWatch/aw-android#53]
Several clients (the ones using aw-client) support to contact a remote server.

There are traces in forums of remote server not being recommended (although reasons are not detailed).
It would be more consistent to support this option for the android app as well.

Could it be considered?

**Comment by kamaradclimber** [comment]
https://github.com/ActivityWatch/aw-watcher-web/issues/26#issuecomment-437813573 seems to be the most authoritative comment I can find on the topic.

**Comment by kamaradclimber** [comment]
I'm really wondering why some clients supports remote server and some others don't.
I understand the security justification but would like to challenge it: it seems users should have the option to run a remote server (especially over their local network).

In the case of android app (and in my use case), the server is accessible on my local network only, so events would be synced only when my phone is connected to my local network. It is not perfect from a security point of view but sufficient for my standard.

@ErikBjare what would be your opinion on this?

**Comment by ErikBjare** [comment]
>I'm really wondering why some clients supports remote server and some others don't.

All clients that use aw-client-python supports using a remote server, since they use the same config file (but discouraged). The web watcher can easily be forked to support it (just change the address and add an allowed CORS origin to the aw-server config).

The reasons we don't put in the effort to make this easy are:

 - It would be redundant once sync is implemented.
 - Security
   - The origin needs to be whitelisted for CORS.
   - The server would need to bind to the public network interface (instead of 127.0.0.1/localhost),m and since the server doesn't have any security we don't want users to expose it to the network.
   - Probably more things I haven't thought about.

>In the case of android app (and in my use case), the server is accessible on my local network only, so events would be synced only when my phone is connected to my local network. It is not perfect from a security point of view but sufficient for my standard.

The Android app/watcher service calls aw-server-rust directly through a JNI wrapper (for performance reasons, and to avoid having to run the server in the background when the app isn't open), so it's not as easy as just pointing it at a different address.

Until we get sync working, the recommended way to collect data from multiple devices on a single server is to manually export and import the relevant buckets.

**Comment by kamaradclimber** [comment]
Thanks for detailed answer.

**Comment by kamaradclimber** [comment]
I'll see what I can do with a fork until synchronization feature is functional.
